"""Init migration

Revision ID: 3ac5813391de
Revises: 713aac056ed6
Create Date: 2026-07-16 20:46:56.339074

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3ac5813391de"
down_revision: str | Sequence[str] | None = "713aac056ed6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
